server:
  port: 8121

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_query_cache: true
      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
      hibernate.connection.autoCommit: false
      hibernate.connection.provider_disables_autocommit: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    database: postgresql
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bettingg
    username: postgres
    password: 6f!v$5-F7ERz79Fn
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: postgresqlPool
      maximumPoolSize: 20
      minimumIdle: 2
      autoCommit: false
      connectionInitSql: SELECT 1